---
- name: Deploy HTML page to web servers
  hosts: all
  become: yes
  tasks:
    - name: Copy HTML file to Nginx web server directory
      ansible.builtin.copy: # обращаемся к модулю для копирования файлов
        src: /home/ubuntu/cmt/index.html # что и откуда в локальной машине
        dest: /usr/share/nginx/html/index.html # место в удаленной машине

    - name: Ensure Nginx is running
      ansible.builtin.service: # аналог systemd.
        name: nginx
        state: started
        enabled: yes
