---
- name: Install and start Nginx web server
  hosts: all
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is enabled and running
      systemd:
        name: nginx
        enabled: yes
        state: started
